export const manyumarTables = {
  companies: "manyumar_empresas",
  categories: "manyumar_categorias",
  companyCategories: "manyumar_categorias_empresa",
  categoryDetails: "manyumar_detalles_categoria",
  incomeOrigins: "manyumar_origenes_ingreso",
  transactions: "manyumar_movimientos",
};

export const manyumarSchema = {
  [manyumarTables.companies]: [
    "id",
    "nombre",
    "icono",
    "orden",
    "creado_en",
    "actualizado_en",
  ],
  [manyumarTables.categories]: [
    "id",
    "nombre",
    "icono",
    "tipo",
    "orden",
    "creado_en",
    "actualizado_en",
  ],
  [manyumarTables.companyCategories]: [
    "id",
    "empresa_id",
    "nombre",
    "icono",
    "tipo",
    "orden",
    "creado_en",
    "actualizado_en",
  ],
  [manyumarTables.categoryDetails]: [
    "id",
    "categoria_padre_id",
    "nombre",
    "icono",
    "orden",
    "creado_en",
    "actualizado_en",
  ],
  [manyumarTables.incomeOrigins]: [
    "id",
    "nombre",
    "icono",
    "orden",
    "creado_en",
    "actualizado_en",
  ],
  [manyumarTables.transactions]: [
    "id",
    "empresa_id",
    "categoria_id",
    "detalle_id",
    "origen_ingreso_id",
    "tipo",
    "monto",
    "fecha_movimiento",
    "descripcion",
    "nombre_empresa",
    "nombre_detalle",
    "nombre_origen_ingreso",
    "creado_en",
    "actualizado_en",
  ],
};
