export const manyumarTables = {
  companies: "manyumar_empresas",
  categories: "manyumar_categorias",
  companyCategories: "manyumar_categorias_empresa",
  categoryDetails: "manyumar_detalles_categoria",
  incomeOrigins: "manyumar_origenes_ingreso",
  transactions: "manyumar_movimientos",
  assets: "manyumar_activos",
  maintenancePlans: "manyumar_planes_mantenimiento",
  maintenanceRequirements: "manyumar_requerimientos_mantenimiento",
};

export const manyumarSchema = {
  [manyumarTables.companies]: [
    "id",
    "nombre",
    "icono",
    "orden",
    "creado_en",
    "actualizado_en",
  ],
  [manyumarTables.categories]: [
    "id",
    "nombre",
    "icono",
    "tipo",
    "orden",
    "creado_en",
    "actualizado_en",
  ],
  [manyumarTables.companyCategories]: [
    "id",
    "empresa_id",
    "nombre",
    "icono",
    "tipo",
    "orden",
    "creado_en",
    "actualizado_en",
  ],
  [manyumarTables.categoryDetails]: [
    "id",
    "categoria_padre_id",
    "nombre",
    "icono",
    "orden",
    "creado_en",
    "actualizado_en",
  ],
  [manyumarTables.incomeOrigins]: [
    "id",
    "nombre",
    "icono",
    "orden",
    "creado_en",
    "actualizado_en",
  ],
  [manyumarTables.transactions]: [
    "id",
    "empresa_id",
    "categoria_id",
    "detalle_id",
    "origen_ingreso_id",
    "tipo",
    "monto",
    "fecha_movimiento",
    "descripcion",
    "nombre_empresa",
    "nombre_detalle",
    "nombre_origen_ingreso",
    "creado_en",
    "actualizado_en",
  ],
  [manyumarTables.assets]: [
    "id",
    "tipo",
    "nombre",
    "identificador",
    "descripcion",
    "activo",
    "creado_en",
    "actualizado_en",
  ],
  [manyumarTables.maintenancePlans]: [
    "id",
    "activo_id",
    "tarea",
    "frecuencia_cantidad",
    "frecuencia_unidad",
    "fecha_inicio",
    "proxima_fecha",
    "vigente",
    "creado_en",
    "actualizado_en",
  ],
  [manyumarTables.maintenanceRequirements]: [
    "id",
    "plan_mantenimiento_id",
    "activo_id",
    "fecha_programada",
    "estado",
    "fecha_aprobacion",
    "aprobado_por",
    "fecha_realizacion",
    "realizado_por",
    "observaciones",
    "creado_en",
    "actualizado_en",
  ],
};
